spring:
  datasource:
    #key: (空格)值
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kgc
    username: root
    password: 1234
    profiles:
      active: prod


logging:
  level:
        #root: info
    com:
      example:
        controller: debug
  file:
    path: logback.xml
server:
  port: 80

